### ISSUE TITLE
BUILD FAILED while building sushi-lib

### ISSUE THREAD

**Issue by kingkan143** [pietrobraione/tardis#14]
![image](https://user-images.githubusercontent.com/67579545/110438417-5d375580-80dc-11eb-83f0-f4231937cb79.png)
![image](https://user-images.githubusercontent.com/67579545/110438497-72ac7f80-80dc-11eb-9f85-868e5df65d96.png)
Build getting failed while building sushi-lib with gradle build -x test.

**Comment by pietrobraione** [comment]
Hi kingkan143; You should build TARDIS from the tardis main project directory, not from the tardis/runtime subproject directory. Try to launch gradle from c:\Users\karan\git\tardis.
